// Code generated by protoc-gendemo-go. DO NOT EDIT.
// versions:
// 	protoc-gendemo-go v1.31.0
// 	protoc        v4.23.3
// source: gps-district-service/gpsquery.proto

package gps_district_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 坐标信息
type Coordinate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 经度，东经为正数，西经为负数
	Longitude float64 `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// 纬度，北纬为正数，南纬为负数
	Latitude float64 `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gps_district_service_gpsquery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_gps_district_service_gpsquery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_gps_district_service_gpsquery_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Coordinate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

// 坐标列表
type CoordinateList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coordinate []*Coordinate `protobuf:"bytes,1,rep,name=coordinate,proto3" json:"coordinate,omitempty"`
}

func (x *CoordinateList) Reset() {
	*x = CoordinateList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gps_district_service_gpsquery_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoordinateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinateList) ProtoMessage() {}

func (x *CoordinateList) ProtoReflect() protoreflect.Message {
	mi := &file_gps_district_service_gpsquery_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinateList.ProtoReflect.Descriptor instead.
func (*CoordinateList) Descriptor() ([]byte, []int) {
	return file_gps_district_service_gpsquery_proto_rawDescGZIP(), []int{1}
}

func (x *CoordinateList) GetCoordinate() []*Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

// 区划码列表
type AdcodeList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Adcode []*wrapperspb.StringValue `protobuf:"bytes,1,rep,name=adcode,proto3" json:"adcode,omitempty"`
}

func (x *AdcodeList) Reset() {
	*x = AdcodeList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gps_district_service_gpsquery_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdcodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdcodeList) ProtoMessage() {}

func (x *AdcodeList) ProtoReflect() protoreflect.Message {
	mi := &file_gps_district_service_gpsquery_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdcodeList.ProtoReflect.Descriptor instead.
func (*AdcodeList) Descriptor() ([]byte, []int) {
	return file_gps_district_service_gpsquery_proto_rawDescGZIP(), []int{2}
}

func (x *AdcodeList) GetAdcode() []*wrapperspb.StringValue {
	if x != nil {
		return x.Adcode
	}
	return nil
}

type IsInQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coordinate *CoordinateList `protobuf:"bytes,1,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	Adcode     string          `protobuf:"bytes,2,opt,name=adcode,proto3" json:"adcode,omitempty"`
}

func (x *IsInQuery) Reset() {
	*x = IsInQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gps_district_service_gpsquery_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsInQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsInQuery) ProtoMessage() {}

func (x *IsInQuery) ProtoReflect() protoreflect.Message {
	mi := &file_gps_district_service_gpsquery_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsInQuery.ProtoReflect.Descriptor instead.
func (*IsInQuery) Descriptor() ([]byte, []int) {
	return file_gps_district_service_gpsquery_proto_rawDescGZIP(), []int{3}
}

func (x *IsInQuery) GetCoordinate() *CoordinateList {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *IsInQuery) GetAdcode() string {
	if x != nil {
		return x.Adcode
	}
	return ""
}

// 是否在区划内结果列表
type InBorderList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Yes []bool `protobuf:"varint,1,rep,packed,name=yes,proto3" json:"yes,omitempty"`
}

func (x *InBorderList) Reset() {
	*x = InBorderList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gps_district_service_gpsquery_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InBorderList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InBorderList) ProtoMessage() {}

func (x *InBorderList) ProtoReflect() protoreflect.Message {
	mi := &file_gps_district_service_gpsquery_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InBorderList.ProtoReflect.Descriptor instead.
func (*InBorderList) Descriptor() ([]byte, []int) {
	return file_gps_district_service_gpsquery_proto_rawDescGZIP(), []int{4}
}

func (x *InBorderList) GetYes() []bool {
	if x != nil {
		return x.Yes
	}
	return nil
}

var File_gps_district_service_gpsquery_proto protoreflect.FileDescriptor

var file_gps_district_service_gpsquery_proto_rawDesc = []byte{
	0x0a, 0x23, 0x67, 0x70, 0x73, 0x2d, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x70, 0x73, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x67, 0x70, 0x73, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61,
	0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x0a, 0x43,
	0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f,
	0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x22, 0x52, 0x0a, 0x0e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x0a, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x70, 0x73, 0x5f,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x0a, 0x63, 0x6f, 0x6f,
	0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x22, 0x42, 0x0a, 0x0a, 0x41, 0x64, 0x63, 0x6f, 0x64,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x06, 0x61, 0x64, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x06, 0x61, 0x64, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x69, 0x0a, 0x09, 0x49,
	0x73, 0x49, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x44, 0x0a, 0x0a, 0x63, 0x6f, 0x6f, 0x72,
	0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x67,
	0x70, 0x73, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x0a, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x64, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x64, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x20, 0x0a, 0x0c, 0x49, 0x6e, 0x42, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x79, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x08, 0x52, 0x03, 0x79, 0x65, 0x73, 0x32, 0xb2, 0x01, 0x0a, 0x12, 0x47, 0x50, 0x53,
	0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x4f, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x24, 0x2e, 0x67, 0x70, 0x73, 0x5f, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x67, 0x70, 0x73, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x63, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x4b, 0x0a, 0x04, 0x49, 0x73, 0x49, 0x6e, 0x12, 0x1f, 0x2e, 0x67, 0x70, 0x73, 0x5f, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x49, 0x73, 0x49, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x22, 0x2e, 0x67, 0x70, 0x73, 0x5f,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x49, 0x6e, 0x42, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x40, 0x5a,
	0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x6e, 0x6b,
	0x65, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x67, 0x70, 0x73, 0x2d, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x67, 0x70, 0x73, 0x5f, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gps_district_service_gpsquery_proto_rawDescOnce sync.Once
	file_gps_district_service_gpsquery_proto_rawDescData = file_gps_district_service_gpsquery_proto_rawDesc
)

func file_gps_district_service_gpsquery_proto_rawDescGZIP() []byte {
	file_gps_district_service_gpsquery_proto_rawDescOnce.Do(func() {
		file_gps_district_service_gpsquery_proto_rawDescData = protoimpl.X.CompressGZIP(file_gps_district_service_gpsquery_proto_rawDescData)
	})
	return file_gps_district_service_gpsquery_proto_rawDescData
}

var file_gps_district_service_gpsquery_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_gps_district_service_gpsquery_proto_goTypes = []interface{}{
	(*Coordinate)(nil),             // 0: gps_district_service.Coordinate
	(*CoordinateList)(nil),         // 1: gps_district_service.CoordinateList
	(*AdcodeList)(nil),             // 2: gps_district_service.AdcodeList
	(*IsInQuery)(nil),              // 3: gps_district_service.IsInQuery
	(*InBorderList)(nil),           // 4: gps_district_service.InBorderList
	(*wrapperspb.StringValue)(nil), // 5: google.protobuf.StringValue
}
var file_gps_district_service_gpsquery_proto_depIdxs = []int32{
	0, // 0: gps_district_service.CoordinateList.coordinate:type_name -> gps_district_service.Coordinate
	5, // 1: gps_district_service.AdcodeList.adcode:type_name -> google.protobuf.StringValue
	1, // 2: gps_district_service.IsInQuery.coordinate:type_name -> gps_district_service.CoordinateList
	1, // 3: gps_district_service.GPSDistrictService.Query:input_type -> gps_district_service.CoordinateList
	3, // 4: gps_district_service.GPSDistrictService.IsIn:input_type -> gps_district_service.IsInQuery
	2, // 5: gps_district_service.GPSDistrictService.Query:output_type -> gps_district_service.AdcodeList
	4, // 6: gps_district_service.GPSDistrictService.IsIn:output_type -> gps_district_service.InBorderList
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gps_district_service_gpsquery_proto_init() }
func file_gps_district_service_gpsquery_proto_init() {
	if File_gps_district_service_gpsquery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gps_district_service_gpsquery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coordinate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gps_district_service_gpsquery_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoordinateList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gps_district_service_gpsquery_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdcodeList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gps_district_service_gpsquery_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsInQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gps_district_service_gpsquery_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InBorderList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gps_district_service_gpsquery_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gps_district_service_gpsquery_proto_goTypes,
		DependencyIndexes: file_gps_district_service_gpsquery_proto_depIdxs,
		MessageInfos:      file_gps_district_service_gpsquery_proto_msgTypes,
	}.Build()
	File_gps_district_service_gpsquery_proto = out.File
	file_gps_district_service_gpsquery_proto_rawDesc = nil
	file_gps_district_service_gpsquery_proto_goTypes = nil
	file_gps_district_service_gpsquery_proto_depIdxs = nil
}
